A:
	g++ -o x A.cpp
	./x
	rm -f x
B:
	g++ -o x B.cpp
	./x
	rm -f x
C:
	g++ -o x C.cpp
	./x
	rm -f x
D:
	g++ -o x D.cpp
	./x
	rm -f x
E:
	g++ -o x E.cpp
	./x
	rm -f x
F:
	g++ -o x F.cpp
	./x
	rm -f x
G:
	g++ -o x G.cpp
	./x
	rm -f x