A:
	g++ -o x A.cpp
	./x
	rm -rf x
B:
	g++ -o x B.cpp
	./x
	rm -rf x
C:
	g++ -o x C.cpp
	./x
	rm -rf x
D:
	g++ -o x D.cpp
	./x
	rm -rf x
E:
	g++ -o x E.cpp
	./x
	rm -rf x
F:
	g++ -o x F.cpp
	./x
	rm -rf x